server:
  tomcat:
    threads:
      max: 50
      min-spare: 5
    connection-timeout: 2s
    keep-alive-timeout: 15s
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PolarBookshop/config-repo
          default-label: main
          timeout: 50
          clone-on-start: true
          force-pull: true

